(function (root, factory) {
  const api = factory();

  if (typeof module === "object" && module.exports) {
    module.exports = api;
  }

  root.GcodeCore = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const VERSION = "1.0.0";
  const FALLBACK_COLORS = [
    "#ef4444",
    "#3b82f6",
    "#22c55e",
    "#f59e0b",
    "#a855f7",
    "#ec4899",
    "#14b8a6",
    "#f97316",
    "#64748b",
    "#eab308",
    "#06b6d4",
    "#8b5cf6",
    "#84cc16",
    "#f43f5e",
    "#0ea5e9",
    "#78716c",
  ];

  const BASIC_COLOR_NAMES = {
    "#000000": "Black",
    "#ffffff": "White",
    "#ff0000": "Red",
    "#00ff00": "Green",
    "#0000ff": "Blue",
    "#ffff00": "Yellow",
    "#f6da5a": "Yellow",
    "#ffa500": "Orange",
    "#800080": "Purple",
    "#808080": "Gray",
    "#c0c0c0": "Silver",
    "#964b00": "Brown",
    "#ffc0cb": "Pink",
  };

  function escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }

  function cleanValue(value) {
    return String(value || "")
      .trim()
      .replace(/^"(.*)"$/, "$1")
      .trim();
  }

  function splitSemicolonList(value) {
    return String(value || "")
      .split(";")
      .map(cleanValue);
  }

  function getConfigValue(lines, key) {
    const pattern = new RegExp("^;\\s*" + escapeRegExp(key) + "\\s*=\\s*(.*)$");

    for (const line of lines) {
      const match = line.match(pattern);
      if (match) {
        return match[1].trim();
      }
    }

    return "";
  }

  function parseDuration(value) {
    const hours = Number((value.match(/(\d+)\s*h/i) || [0, 0])[1]);
    const minutes = Number((value.match(/(\d+)\s*m/i) || [0, 0])[1]);
    const seconds = Number((value.match(/(\d+)\s*s/i) || [0, 0])[1]);
    return hours * 3600 + minutes * 60 + seconds;
  }

  function normalizeHex(value, fallback) {
    const color = String(value || "").trim().toLowerCase();
    return /^#[0-9a-f]{6}$/.test(color) ? color : fallback;
  }

  function describeColor(hex) {
    return BASIC_COLOR_NAMES[String(hex || "").toLowerCase()] || "";
  }

  function cleanProfileName(profile) {
    return cleanValue(profile)
      .replace(/\s*@.*$/, "")
      .replace(/^Generic\s+/i, "")
      .trim();
  }

  function parseMetadata(lines) {
    const generated = lines.find((line) => /^;\s*generated by /i.test(line)) || "";
    const timeLine =
      lines.find((line) => /^;\s*model printing time:/i.test(line)) || "";
    const totalTimeMatch = timeLine.match(/total estimated time:\s*([^;]+)/i);
    const modelTimeMatch = timeLine.match(/model printing time:\s*([^;]+)/i);
    const totalLayers =
      Number(
        (
          lines.find((line) => /^;\s*total layer number:/i.test(line)) || ""
        ).match(/(\d+)/)?.[1]
      ) || Number(getConfigValue(lines, "total_layer_count")) || 0;
    const activeLine =
      lines.find((line) => /^;\s*filament:\s*[\d,\s]+$/i.test(line)) || "";
    const activeTools = (activeLine.match(/:\s*(.*)$/)?.[1] || "")
      .split(",")
      .map((value) => Number(value.trim()) - 1)
      .filter((value) => Number.isInteger(value) && value >= 0 && value <= 15);

    return {
      slicer: generated.replace(/^;\s*generated by\s*/i, "").trim(),
      printer:
        cleanValue(getConfigValue(lines, "printer_model")) ||
        cleanValue(getConfigValue(lines, "printer_variant")) ||
        "Bambu printer",
      totalLayers,
      totalTimeSeconds: parseDuration(totalTimeMatch?.[1] || ""),
      modelTimeSeconds: parseDuration(modelTimeMatch?.[1] || ""),
      maxZ: Number(
        (
          lines.find((line) => /^;\s*max_z_height:/i.test(line)) || ""
        ).match(/([\d.]+)/)?.[1]
      ),
      activeTools,
      colors: splitSemicolonList(getConfigValue(lines, "filament_colour")),
      types: splitSemicolonList(getConfigValue(lines, "filament_type")),
      profiles: splitSemicolonList(
        getConfigValue(lines, "filament_settings_id")
      ),
      vendors: splitSemicolonList(getConfigValue(lines, "filament_vendor")),
      temperatures: splitSemicolonList(
        getConfigValue(lines, "nozzle_temperature")
      ).map(Number),
    };
  }

  function isInside(index, ranges) {
    return ranges.some((range) => index >= range.start && index <= range.end);
  }

  function findLastIndex(lines, predicate) {
    for (let index = lines.length - 1; index >= 0; index -= 1) {
      if (predicate(lines[index], index)) {
        return index;
      }
    }

    return -1;
  }

  function getToolFromBlock(block) {
    for (const line of block) {
      const match = line.match(/^\s*T(\d+)\s*(?:;.*)?$/);
      if (match && Number(match[1]) <= 15) {
        return Number(match[1]);
      }
    }

    for (const line of block) {
      const match = line.match(/^\s*M620\s+S(\d+)A\b/);
      if (match && Number(match[1]) <= 15) {
        return Number(match[1]);
      }
    }

    return null;
  }

  function getTemperature(block) {
    const temperatures = [];

    for (const line of block) {
      const match = line.match(/^\s*M10[49]\s+S([\d.]+)/);
      if (match) {
        temperatures.push(Number(match[1]));
      }
    }

    return temperatures.length ? Math.max(...temperatures) : null;
  }

  function detectStructuredToolChanges(lines) {
    const events = [];
    const protectedRanges = [];

    for (let index = 0; index < lines.length; index += 1) {
      if (!/^\s*;\s*CP TOOLCHANGE START\b/i.test(lines[index])) {
        continue;
      }

      let blockEnd = index + 1;
      while (
        blockEnd < lines.length &&
        !/^\s*;\s*CP TOOLCHANGE END\b/i.test(lines[blockEnd])
      ) {
        blockEnd += 1;
      }

      if (blockEnd >= lines.length) {
        continue;
      }

      const block = lines.slice(index, blockEnd + 1);
      const targetTool = getToolFromBlock(block);
      const relativeStart = block.findIndex((line) =>
        /^\s*M1007\s+S0\b/.test(line)
      );
      const fallbackStart = block.findIndex((line) =>
        /^\s*M620\s+S\d+A\b/.test(line)
      );
      const relativeEnd = findLastIndex(block, (line) =>
        /^\s*M1007\s+S1\b/.test(line)
      );
      const fallbackEnd = findLastIndex(block, (line) =>
        /^\s*M621\s+S\d+A\b/.test(line)
      );
      const materialMatch = block
        .join("\n")
        .match(/;\s*material\s*:\s*(.*?)\s*->\s*(.*?)\s*$/im);

      if (
        targetTool !== null &&
        (relativeStart >= 0 || fallbackStart >= 0) &&
        (relativeEnd >= 0 || fallbackEnd >= 0)
      ) {
        const transformStart =
          index + (relativeStart >= 0 ? relativeStart : fallbackStart);
        const transformEnd =
          index + (relativeEnd >= 0 ? relativeEnd : fallbackEnd);

        events.push({
          id: "",
          kind: "change",
          blockStart: index,
          blockEnd,
          transformStart,
          transformEnd,
          targetTool,
          fromMaterial: cleanValue(materialMatch?.[1] || ""),
          toMaterial: cleanValue(materialMatch?.[2] || ""),
          temperature: getTemperature(
            lines.slice(transformStart, transformEnd + 1)
          ),
          structured: true,
        });
      }

      protectedRanges.push({ start: index, end: blockEnd });
      index = blockEnd;
    }

    return { events, protectedRanges };
  }

  function detectGenericToolChanges(lines, protectedRanges) {
    const events = [];
    const firstLayerIndex = lines.findIndex((line) =>
      /^;\s*CHANGE_LAYER\b/i.test(line)
    );

    for (let index = 0; index < lines.length; index += 1) {
      if (isInside(index, protectedRanges)) {
        continue;
      }

      const startMatch = lines[index].match(/^\s*M620\s+S(\d+)A\b/);
      if (!startMatch || Number(startMatch[1]) > 15) {
        continue;
      }

      const targetTool = Number(startMatch[1]);
      let end = index + 1;

      while (
        end < lines.length &&
        !new RegExp("^\\s*M621\\s+S" + targetTool + "A\\b").test(lines[end])
      ) {
        end += 1;
      }

      if (end >= lines.length) {
        continue;
      }

      let transformStart = index;
      for (
        let back = index - 1;
        back >= Math.max(0, index - 6);
        back -= 1
      ) {
        if (/^\s*M620\s+M\b/.test(lines[back])) {
          transformStart = back;
          break;
        }
        if (/^\s*M1007\s+S0\b/.test(lines[back])) {
          transformStart = back;
          break;
        }
        if (lines[back].trim() && !/^\s*;/.test(lines[back])) {
          break;
        }
      }

      let transformEnd = end;
      for (
        let forward = end + 1;
        forward < Math.min(lines.length, end + 6);
        forward += 1
      ) {
        if (
          !lines[forward].trim() ||
          /^\s*G392\s+S0\b/.test(lines[forward]) ||
          /^\s*M1007\s+S1\b/.test(lines[forward])
        ) {
          transformEnd = forward;
          continue;
        }
        break;
      }

      events.push({
        id: "",
        kind:
          firstLayerIndex < 0 || transformStart < firstLayerIndex
            ? "initial"
            : "change",
        blockStart: transformStart,
        blockEnd: transformEnd,
        transformStart,
        transformEnd,
        targetTool,
        fromMaterial: "",
        toMaterial: "",
        temperature: getTemperature(
          lines.slice(transformStart, transformEnd + 1)
        ),
        structured: false,
      });

      protectedRanges.push({ start: transformStart, end: transformEnd });
      index = transformEnd;
    }

    return events;
  }

  function detectRawToolChanges(lines, protectedRanges) {
    const events = [];

    for (let index = 0; index < lines.length; index += 1) {
      if (isInside(index, protectedRanges)) {
        continue;
      }

      const match = lines[index].match(/^\s*T(\d+)\s*(?:;.*)?$/);
      if (!match || Number(match[1]) > 15) {
        continue;
      }

      events.push({
        id: "",
        kind: "raw",
        blockStart: index,
        blockEnd: index,
        transformStart: index,
        transformEnd: index,
        targetTool: Number(match[1]),
        fromMaterial: "",
        toMaterial: "",
        temperature: null,
        structured: false,
      });
      protectedRanges.push({ start: index, end: index });
    }

    return events;
  }

  function detectCleanupBlocks(lines) {
    const blocks = [];

    for (let index = 0; index < lines.length; index += 1) {
      if (!/^\s*M620\s+S255\b/.test(lines[index])) {
        continue;
      }

      let end = index + 1;
      while (end < lines.length && !/^\s*M621\s+S255\b/.test(lines[end])) {
        end += 1;
      }

      if (end >= lines.length) {
        continue;
      }

      let start = index;
      for (
        let back = index - 1;
        back >= Math.max(0, index - 5);
        back -= 1
      ) {
        if (/^\s*;\s*pull back filament to AMS\b/i.test(lines[back])) {
          start = back;
          break;
        }
        if (lines[back].trim() && !/^\s*;/.test(lines[back])) {
          break;
        }
      }

      blocks.push({ start, end });
      index = end;
    }

    return blocks;
  }

  function attachEventContext(lines, events, metadata) {
    const eventsByStart = new Map();
    for (const event of events) {
      const list = eventsByStart.get(event.blockStart) || [];
      list.push(event);
      eventsByStart.set(event.blockStart, list);
    }

    let layer = 0;
    let totalLayers = metadata.totalLayers;
    let z = null;
    let remainingMinutes = null;
    let progress = null;

    for (let index = 0; index < lines.length; index += 1) {
      const layerMatch = lines[index].match(
        /^;\s*layer num\/total_layer_count:\s*(\d+)\/(\d+)/i
      );
      const zMatch = lines[index].match(/^;\s*Z_HEIGHT:\s*([\d.]+)/i);
      const progressMatch = lines[index].match(
        /^\s*M73\s+P([\d.]+)(?:\s+R([\d.]+))?/
      );

      if (layerMatch) {
        layer = Number(layerMatch[1]);
        totalLayers = Number(layerMatch[2]) || totalLayers;
      }
      if (zMatch) {
        z = Number(zMatch[1]);
      }
      if (progressMatch) {
        progress = Number(progressMatch[1]);
        if (progressMatch[2] !== undefined) {
          remainingMinutes = Number(progressMatch[2]);
        }
      }

      for (const event of eventsByStart.get(index) || []) {
        event.layer = event.kind === "initial" ? 0 : layer;
        event.totalLayers = totalLayers;
        event.z = event.kind === "initial" ? 0 : z;
        event.progress = event.kind === "initial" ? 0 : progress;
        event.remainingMinutes =
          event.kind === "initial" ? null : remainingMinutes;
        event.elapsedSeconds =
          event.kind === "initial"
            ? 0
            : metadata.totalTimeSeconds && remainingMinutes !== null
              ? Math.max(
                  0,
                  metadata.totalTimeSeconds - remainingMinutes * 60
                )
              : progress !== null && metadata.totalTimeSeconds
                ? Math.round(
                    metadata.totalTimeSeconds * (progress / 100)
                  )
                : null;
      }
    }
  }

  function buildFilaments(metadata, events) {
    const referenced = new Set(metadata.activeTools);
    for (const event of events) {
      referenced.add(event.targetTool);
      if (event.fromTool !== null && event.fromTool !== undefined) {
        referenced.add(event.fromTool);
      }
    }

    return [...referenced]
      .filter((tool) => Number.isInteger(tool) && tool >= 0 && tool <= 15)
      .sort((a, b) => a - b)
      .map((tool) => {
        const color = normalizeHex(
          metadata.colors[tool],
          FALLBACK_COLORS[tool % FALLBACK_COLORS.length]
        );
        const type = cleanValue(metadata.types[tool]);
        const profile = cleanProfileName(metadata.profiles[tool]);
        const colorName = describeColor(color);
        const defaultName =
          [colorName, type].filter(Boolean).join(" ") ||
          profile ||
          "Filament " + (tool + 1);

        return {
          tool,
          slot: tool + 1,
          color,
          colorName,
          type: type || "Unknown",
          profile,
          vendor: cleanValue(metadata.vendors[tool]),
          temperature: metadata.temperatures[tool] || null,
          defaultName,
        };
      });
  }

  function analyzeGcode(text) {
    const newline = text.includes("\r\n") ? "\r\n" : "\n";
    const hadFinalNewline = /\r?\n$/.test(text);
    const lines = text.replace(/\r\n/g, "\n").split("\n");
    const metadata = parseMetadata(lines);
    const structured = detectStructuredToolChanges(lines);
    const protectedRanges = [...structured.protectedRanges];
    const generic = detectGenericToolChanges(lines, protectedRanges);
    const raw = detectRawToolChanges(lines, protectedRanges);
    const events = [...structured.events, ...generic, ...raw].sort(
      (a, b) => a.transformStart - b.transformStart
    );
    const cleanupBlocks = detectCleanupBlocks(lines);
    let currentTool = null;

    for (const event of events) {
      event.fromTool = currentTool;
      currentTool = event.targetTool;
    }

    attachEventContext(lines, events, metadata);

    events.forEach((event, index) => {
      event.id = "event-" + (index + 1);
      event.number = index + 1;
      event.line = event.blockStart + 1;
    });

    return {
      version: VERSION,
      text,
      lines,
      newline,
      hadFinalNewline,
      metadata,
      events,
      filaments: buildFilaments(metadata, events),
      cleanupBlocks,
      lineCount: hadFinalNewline ? lines.length - 1 : lines.length,
      byteCount:
        typeof TextEncoder !== "undefined"
          ? new TextEncoder().encode(text).length
          : text.length,
    };
  }

  function formatElapsed(seconds) {
    if (seconds === null || seconds === undefined || Number.isNaN(seconds)) {
      return "unknown time";
    }

    const totalMinutes = Math.max(0, Math.round(seconds / 60));
    const hours = Math.floor(totalMinutes / 60);
    const minutes = totalMinutes % 60;
    return hours + ":" + String(minutes).padStart(2, "0");
  }

  function safeComment(value) {
    return String(value || "")
      .replace(/[\r\n]+/g, " ")
      .replace(/[^\x20-\x7E]/g, "")
      .trim();
  }

  function getFilament(analysis, tool) {
    return analysis.filaments.find((filament) => filament.tool === tool) || null;
  }

  function createManualBlock(analysis, event, options) {
    const target = getFilament(analysis, event.targetTool);
    const from = getFilament(analysis, event.fromTool);
    const names = options.names || {};
    const targetName = safeComment(
      names[event.targetTool] || target?.defaultName || "Filament " + (event.targetTool + 1)
    );
    const fromName = safeComment(
      names[event.fromTool] || from?.defaultName || event.fromMaterial || ""
    );
    const action =
      event.kind === "initial"
        ? "Load " + targetName
        : "Change " + (fromName || "filament") + " -> " + targetName;
    const context = [
      event.layer !== null && event.layer !== undefined
        ? "Layer " + event.layer + "/" + (event.totalLayers || "?")
        : "",
      event.z !== null && event.z !== undefined ? "Z " + event.z + " mm" : "",
      "about " + formatElapsed(event.elapsedSeconds),
    ]
      .filter(Boolean)
      .join(" | ");
    const original = analysis.lines.slice(
      event.transformStart,
      event.transformEnd + 1
    );
    const hadMassEstimation = original.some((line) =>
      /^\s*M1007\s+S0\b/.test(line)
    );
    const hadClogDisable = original.some((line) =>
      /^\s*G392\s+S0\b/.test(line)
    );
    const temperature =
      event.temperature || target?.temperature || null;
    const block = [
      ";===== MANUAL FILAMENT CHANGE START =====",
      "; " + action,
      "; " + context,
    ];

    if (hadMassEstimation) {
      block.push("M1007 S0 ; pause mass estimation during manual change");
    }
    if (hadClogDisable) {
      block.push("G392 S0 ; disable nozzle clog detection during change");
    }

    block.push("M400 ; finish queued moves");

    if (options.waitForTemperature !== false && temperature) {
      block.push(
        "M109 S" +
          Number(temperature).toFixed(
            Number.isInteger(Number(temperature)) ? 0 : 1
          ) +
          " ; wait for a safe manual-change temperature"
      );
    }

    const pauseCommand = String(options.pauseCommand || "M400 U1")
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);
    block.push(...pauseCommand.map((line) => line + " ; manual change pause"));
    block.push("M400 ; wait for resume");

    if (options.setFilamentType !== false && target?.type) {
      block.push(
        "M1002 set_filament_type:" +
          safeComment(target.type).replace(/\s+/g, "_").toUpperCase()
      );
    }

    block.push("G92 E0 ; reset relative extrusion reference");

    if (hadMassEstimation) {
      block.push("M1007 S1 ; resume mass estimation");
    }

    block.push(";===== MANUAL FILAMENT CHANGE END =====");
    return block;
  }

  function transformGcode(analysis, options) {
    const selected = new Set(
      options.selectedEventIds || analysis.events.map((event) => event.id)
    );
    const replacements = new Map();
    let convertedCount = 0;

    for (const event of analysis.events) {
      if (!selected.has(event.id)) {
        continue;
      }

      replacements.set(event.transformStart, {
        end: event.transformEnd,
        lines: createManualBlock(analysis, event, options),
      });
      convertedCount += 1;
    }

    let cleanupRemoved = 0;
    if (options.removeAmsCleanup !== false) {
      for (const cleanup of analysis.cleanupBlocks) {
        replacements.set(cleanup.start, {
          end: cleanup.end,
          lines: [
            "; AMS end-of-print unload removed for manual filament operation",
          ],
        });
        cleanupRemoved += 1;
      }
    }

    const output = [];
    for (let index = 0; index < analysis.lines.length; index += 1) {
      const replacement = replacements.get(index);
      if (replacement) {
        output.push(...replacement.lines);
        index = replacement.end;
        continue;
      }

      if (/^;\s*manual_filament_change\s*=\s*0\s*$/.test(analysis.lines[index])) {
        output.push("; manual_filament_change = 1");
      } else {
        output.push(analysis.lines[index]);
      }
    }

    const headerIndex = output.findIndex((line) =>
      /^;\s*HEADER_BLOCK_START\b/.test(line)
    );
    const noteIndex = headerIndex >= 0 ? headerIndex + 1 : 0;
    output.splice(
      noteIndex,
      0,
      "; converted to manual filament changes by Manual Filament Shift " +
        VERSION,
      "; converted events: " + convertedCount
    );

    let text = output.join(analysis.newline);
    if (analysis.hadFinalNewline && !text.endsWith(analysis.newline)) {
      text += analysis.newline;
    }

    const remainingAmsCommands = output
      .map((line, index) => ({ line, number: index + 1 }))
      .filter(
        (entry) =>
          /^\s*M62[01]\s+S(?:\d+A|255)\b/.test(entry.line) ||
          /^\s*T(?:[0-9]|1[0-5]|255)\s*(?:;.*)?$/.test(entry.line)
      );

    return {
      text,
      convertedCount,
      cleanupRemoved,
      remainingAmsCommands,
      outputLineCount: output.length,
    };
  }

  return {
    VERSION,
    analyzeGcode,
    transformGcode,
    formatElapsed,
  };
});
