const assert = require("node:assert/strict");
const { analyzeGcode, transformGcode } = require("./gcode-core.js");

const source = [
  "; HEADER_BLOCK_START",
  "; generated by OrcaSlicer test fixture",
  "; model printing time: 4h 38m 30s; total estimated time: 4h 45m 3s",
  "; total layer number: 180",
  "; filament: 4,5",
  "; HEADER_BLOCK_END",
  "; filament_colour = #000000;#ffffff;#ffffff;#f6da5a;#ffffff",
  "; filament_type = PLA;PLA;PETG;PLA;TPU",
  '; filament_settings_id = "A";"B";"C";"Yellow PLA";"White TPU"',
  "; filament_vendor = A;B;C;Overture;Generic",
  "; nozzle_temperature = 220,220,255,220,240",
  "; manual_filament_change = 0",
  "M620 M ; enable remap",
  "M620 S4A",
  "T4",
  "M621 S4A",
  "; CHANGE_LAYER",
  "; Z_HEIGHT: 5.8",
  "; layer num/total_layer_count: 29/180",
  "M73 P27 R208",
  "; CP TOOLCHANGE START",
  "; material : TPU -> PLA",
  "M1007 S0",
  "G392 S0",
  "M620 S3A",
  "M104 S240",
  "T3",
  "M621 S3A",
  "G392 S0",
  "M1007 S1",
  "; CP TOOLCHANGE WIPE",
  "G1 X50 E1",
  "; CP TOOLCHANGE END",
  "; CHANGE_LAYER",
  "; Z_HEIGHT: 6",
  "; layer num/total_layer_count: 30/180",
  "M73 P28 R202",
  "; CP TOOLCHANGE START",
  "; material : PLA -> TPU",
  "M1007 S0",
  "G392 S0",
  "M620 S4A",
  "M104 S250",
  "T4",
  "M621 S4A",
  "G392 S0",
  "M1007 S1",
  "; CP TOOLCHANGE WIPE",
  "G1 X60 E1",
  "; CP TOOLCHANGE END",
  "; pull back filament to AMS",
  "M620 S255",
  "T255",
  "M621 S255",
  "M104 S0",
].join("\n");

const analysis = analyzeGcode(source);

assert.equal(analysis.metadata.totalLayers, 180);
assert.equal(analysis.events.length, 3);
assert.deepEqual(
  analysis.events.map((event) => event.kind),
  ["initial", "change", "change"]
);
assert.deepEqual(
  analysis.events.map((event) => event.targetTool),
  [4, 3, 4]
);
assert.deepEqual(
  analysis.events.map((event) => event.layer),
  [0, 29, 30]
);
assert.equal(analysis.cleanupBlocks.length, 1);

const converted = transformGcode(analysis, {
  selectedEventIds: analysis.events.map((event) => event.id),
  names: {
    3: "Yellow PLA",
    4: "White TPU",
  },
  pauseCommand: "M400 U1",
  waitForTemperature: true,
  removeAmsCleanup: true,
  setFilamentType: true,
});

assert.equal(converted.convertedCount, 3);
assert.equal(converted.cleanupRemoved, 1);
assert.equal((converted.text.match(/^M400 U1\b/gm) || []).length, 3);
assert.equal((converted.text.match(/^; CP TOOLCHANGE WIPE\b/gm) || []).length, 2);
assert.equal(converted.remainingAmsCommands.length, 0);
assert.doesNotMatch(converted.text, /^M620 S[34]A\b/gm);
assert.doesNotMatch(converted.text, /^M621 S[34]A\b/gm);
assert.doesNotMatch(converted.text, /^T[34]\s*$/gm);
assert.doesNotMatch(converted.text, /^T255\s*$/gm);
assert.doesNotMatch(converted.text, /^M621 S255\b/gm);
assert.match(converted.text, /^; manual_filament_change = 1$/gm);
assert.match(converted.text, /Change White TPU -> Yellow PLA/);
assert.match(converted.text, /Change Yellow PLA -> White TPU/);

const rawSource = [
  "; total layer number: 2",
  "; filament_colour = #ff0000;#0000ff",
  "; filament_type = PLA;PLA",
  "; layer num/total_layer_count: 1/2",
  "T1",
  "G1 X10",
].join("\n");
const rawAnalysis = analyzeGcode(rawSource);
assert.equal(rawAnalysis.events.length, 1);
assert.equal(rawAnalysis.events[0].kind, "raw");
assert.equal(
  (
    transformGcode(rawAnalysis, {
      selectedEventIds: [rawAnalysis.events[0].id],
      pauseCommand: "M400 U1",
    }).text.match(/^M400 U1\b/gm) || []
  ).length,
  1
);

console.log(
  `PASS: ${analysis.events.length} pauses found and no actionable AMS commands remain.`
);
